version: "3.8"

services:
  feishu-github-tracker:
    image: ghcr.io/hnrobert/feishu-github-tracker:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: feishu-github-tracker
    restart: unless-stopped
    ports:
      - "4594:4594"
    volumes:
      - ./configs:/app/configs:ro
      - ./log:/app/log
    environment:
      - CONFIG_DIR=/app/configs
      - LOG_DIR=/app/log
      - TZ=Asia/Shanghai
    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       "wget --quiet --tries=1 --spider http://localhost:4594/health || exit 1",
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s
