# =========================================
# events.yaml
# -----------------------------------------
# 定义支持的GitHub事件结构
# 可通过 `alias` 在repo中快速引用
# =========================================

# 模板集合，用于在repos.yaml中引用
# 注意：如果在模板里包含了一个完整事件（例如使用 `push:`），
# 并且在该事件下没有进一步指定分支/类型等条件，我们会把它视为“全选”（匹配该事件的所有子类型）。
event_sets:
  # "all" 模板：包含GitHub支持的全部事件（包含所有事件）
  all:
    branch_protection_configuration:
    branch_protection_rule:
    branches:
    check_run:
    check_suite:
    code_scanning_alert:
    commit_comment:
    create:
    custom_property:
    custom_property_values:
    delete:
    dependabot_alert:
    deploy_key:
    deployment:
    deployment_protection_rule:
    deployment_review:
    deployment_status:
    discussion:
    discussion_comment:
    fork:
    github_app_authorization:
    gollum:
    installation:
    installation_repositories:
    installation_target:
    issue_comment:
    issue_dependencies:
    issues:
    label:
    marketplace_purchase:
    member:
    membership:
    merge_group:
    meta:
    milestone:
    org_block:
    organization:
    package:
    page_build:
    personal_access_token_request:
    ping:
    project:
    project_card:
    project_column:
    projects_v2:
    projects_v2_item:
    projects_v2_status_update:
    public:
    pull_request:
    pull_request_review:
    pull_request_review_comment:
    pull_request_review_thread:
    push:
    registry_package:
    release:
    repository:
    repository_advisory:
    repository_dispatch:
    repository_import:
    repository_ruleset:
    repository_vulnerability_alert:
    secret_scanning_alert:
    secret_scanning_alert_location:
    secret_scanning_scan:
    security_advisory:
    security_and_analysis:
    sponsorship:
    star:
    status:
    sub_issues:
    team:
    team_add:
    types:
    watch:
    workflow_dispatch:
    workflow_job:
    workflow_run:
  
  # "basic" 模板：适合中小型项目，一般常用事件
  basic:
    discussion:
    discussion_comment:
    issue_comment:
    issues:
    package:
    pull_request:
    pull_request_review:
    pull_request_review_comment:
    push:
    release:
  
  # 自定义模板：可按需添加事件并细化自定义新的 event_sets（示例）
  custom:
    discussion:
      types:
        - created
        - answered
    issues:
      types:
        - opened
        - closed
        - reopened
    pull_request:
      branches:
        - main
        - develop
        - release/*
      types:
        - opened
        - closed
        - reopened
    push:
      branches:
        - main
        - develop
        - release/*
    release:
      types:
        - published
        - edited

# 下面是完整事件列表，供模板引用或自定义精细化配置，也可以直接在 repos.yaml 中每个仓库的 events 中使用。如果要 CV 请注意缩进。
events:
  branch_protection_configuration:
    types:
      - disabled
      - enabled
  branch_protection_rule:
    types:
      - created
      - deleted
      - edited
  check_run:
    types:
      - created
      - completed
      - rerequested
      - requested_action
  check_suite:
    types:
      - completed
      - requested
      - rerequested
  code_scanning_alert:
    types:
      - appeared_in_branch
      - closed_by_user
      - created
      - fixed
      - reopened
      - reopened_by_user
  commit_comment:
    types:
      - created
  create:
  custom_property:
    types:
      - created
      - deleted
      - promote_to_enterprise
      - updated
  custom_property_values:
    types:
      - updated
  delete:
  dependabot_alert:
    types:
      - auto_dismissed
      - auto_reopened
      - created
      - dismissed
      - fixed
      - reintroduced
      - reopened
  deploy_key:
    types:
      - created
      - deleted
  deployment:
  deployment_protection_rule:
    types:
      - requested
  deployment_review:
    types:
      - approved
      - rejected
      - requested
  deployment_status:
  discussion:
    types:
      - created
      - edited
      - deleted
      - transferred
      - pinned
      - unpinned
      - locked
      - unlocked
      - labeled
      - unlabeled
      - answered
      - unanswered
  discussion_comment:
    types:
      - created
      - edited
      - deleted
  fork:
  github_app_authorization:
    types:
      - revoked
  gollum:
  installation:
    types:
      - created
      - deleted
      - new_permissions_accepted
      - suspend
      - unsuspend
  installation_repositories:
    types:
      - added
      - removed
  installation_target:
    types:
      - renamed
  issue_comment:
    types:
      - created
      - edited
      - deleted
  issue_dependencies:
    types:
      - blocked_by_added
      - blocked_by_removed
      - blocking_added
      - blocking_removed
  issues:
    types:
      - opened
      - closed
      - reopened
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - edited
      - milestoned
      - demilestoned
      - transferred
      - deleted
      - pinned
      - unpinned
      - locked
      - unlocked
      - typed
      - untyped
  label:
    types:
      - created
      - deleted
      - edited
  marketplace_purchase:
    types:
      - cancelled
      - changed
      - pending_change
      - pending_change_cancelled
      - purchased
  member:
    types:
      - added
      - removed
      - edited
  membership:
    types:
      - added
      - removed
  merge_group:
    types:
      - checks_requested
      - destroyed
  meta:
    types:
      - deleted
  milestone:
    types:
      - created
      - closed
      - opened
      - edited
      - deleted
  org_block:
    types:
      - blocked
      - unblocked
  organization:
    types:
      - member_added
      - member_removed
      - member_invited
  package:
    types:
      - published
      - updated
  page_build:
  personal_access_token_request:
    types:
      - approved
      - cancelled
      - created
      - denied
  ping:
  project:
    types:
      - created
      - updated
      - closed
      - reopened
      - deleted
  project_card:
    types:
      - created
      - moved
      - converted
      - edited
      - deleted
  project_column:
    types:
      - created
      - updated
      - moved
      - deleted
  projects_v2:
    types:
      - closed
      - created
      - deleted
      - edited
      - reopened
  projects_v2_item:
    types:
      - archived
      - converted
      - created
      - deleted
      - edited
      - reordered
      - restored
  projects_v2_status_update:
    types:
      - created
      - deleted
      - edited
  public:
  pull_request:
    branches:
      - "*"
    types:
      - opened
      - closed
      - reopened
      - synchronize
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - review_requested
      - review_request_removed
      - ready_for_review
      - converted_to_draft
      - auto_merge_enabled
      - auto_merge_disabled
      - dequeued
      - enqueued
      - edited
      - locked
      - unlocked
      - milestoned
      - demilestoned
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
  pull_request_review_comment:
    types:
      - created
      - edited
      - deleted
  pull_request_review_thread:
    types:
      - resolved
      - unresolved
  push:
    branches:
      - "*"
  registry_package:
    types:
      - published
      - updated
  release:
    types:
      - published
      - unpublished
      - created
      - edited
      - deleted
      - prereleased
      - released
  repository:
    types:
      - created
      - deleted
      - archived
      - unarchived
      - edited
      - renamed
      - transferred
      - publicized
      - privatized
  repository_advisory:
    types:
      - published
      - reported
  repository_dispatch:
  repository_import:
  repository_ruleset:
    types:
      - created
      - deleted
      - edited
  repository_vulnerability_alert:
    types:
      - create
      - dismiss
      - reopen
      - resolve
  secret_scanning_alert:
    types:
      - created
      - publicly_leaked
      - reopened
      - resolved
      - validated
  secret_scanning_alert_location:
    types:
      - created
  secret_scanning_scan:
    types:
      - completed
  security_advisory:
    types:
      - published
      - updated
      - withdrawn
  security_and_analysis:
  sponsorship:
    types:
      - cancelled
      - created
      - edited
      - pending_cancellation
      - pending_tier_change
      - tier_changed
  star:
    types:
      - created
      - deleted
  status:
  sub_issues:
    types:
      - parent_issue_added
      - parent_issue_removed
      - sub_issue_added
      - sub_issue_removed
  team:
    types:
      - created
      - deleted
      - edited
      - added_to_repository
      - removed_from_repository
  team_add:
  watch:
    types:
      - started
  workflow_dispatch:
  workflow_job:
    types:
      - completed
      - in_progress
      - queued
      - waiting
  workflow_run:
    types:
      - completed
      - requested
      - in_progress
