# =========================================
# feishu-bots.yaml
# -----------------------------------------
# 存放所有飞书机器人的别名和Webhook URL
# 可在repos.yaml中通过alias引用
# =========================================

feishu_bots:
  - alias: "dev-team" # 可以在 repos.yaml 中通过该别名引用这个链接
    url: "https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxxx"

  - alias: "ops-team"
    url: "https://open.feishu.cn/open-apis/bot/v2/hook/yyyyyyy"

  - alias: "org-notify"
    url: "https://open.feishu.cn/open-apis/bot/v2/hook/zzzzzzz"
