# =========================================
# server.yaml
# -----------------------------------------
# 用于定义 Webhook 服务本体的监听配置、日志、校验等信息
# =========================================

server:
  host: "0.0.0.0" # Webhook监听主机
  port: 8080 # Webhook监听端口
  secret: "your_secret" # 用于验证GitHub X-Hub-Signature的密钥
  log_level: "info" # 可选: debug, info, warn, error
  max_payload_size: 5MB # 限制单次Webhook body大小
  timeout: 15 # 单次请求处理超时 (秒)

# 允许的来源（用于白名单过滤，可选）
allowed_sources:
  - "github.com"
  - "api.github.com"
  - "your-github-enterprise-domain.com"
