name: CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - ".github/workflows/ci.yml"
      - "Dockerfile"
      - ".dockerignore"
      - "**/*.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go with cache
        uses: ./.github/actions/setup-go
        with:
          go-version: "1.21"

      - name: Run tests
        run: go test -v ./...

      - name: Run go vet
        run: go vet ./...

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'))
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        id: tag
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          if [ "${BRANCH}" = "main" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          elif [ "${BRANCH}" = "develop" ]; then
            echo "tag=develop" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          provenance: false # Disable provenance to avoid unknown/unknown
          sbom: false # Disable sbom to avoid unknown/unknown
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
